"""Loads historical season data imported from the spreadsheet CSVs.

Generated by `scripts/import_historic.py` — produces three JSON files:
- standings.json: per-day [{date, drafters, standings:[{drafter,rank,total,full_total}]}]
- picks.json:     per-pick [{date, drafter, player_name, score, role}]
- team_counts.json: {team_abbr: appearances_so_far} for the schedule balancer
"""

from __future__ import annotations

import json
import os

_DATA_DIR = os.path.join(os.path.dirname(os.path.dirname(__file__)), "data", "historic")


def _load(name: str, default):
    path = os.path.join(_DATA_DIR, name)
    if not os.path.exists(path):
        return default
    try:
        with open(path) as f:
            return json.load(f)
    except Exception:
        return default


def standings() -> list[dict]:
    return _load("standings.json", [])


def picks() -> list[dict]:
    return _load("picks.json", [])


def team_counts() -> dict[str, int]:
    return _load("team_counts.json", {})
