"""Loads historical season data imported from the spreadsheet CSVs.

Generated by `scripts/import_historic.py` — produces three JSON files:
- standings.json: per-day [{date, drafters, standings:[{drafter,rank,total,full_total}]}]
- picks.json:     per-pick [{date, drafter, player_name, score, role}]
- team_counts.json: {team_abbr: appearances_so_far} for the schedule balancer
"""

from __future__ import annotations

import json
import os

_DATA_DIR = os.path.join(os.path.dirname(__file__), "data", "historic")

# The spreadsheet uses a few non-canonical team abbreviations that differ from
# the MLB Stats API. Map them so historic counts merge correctly with live
# slate-builder counts (which always come from the API).
TEAM_ALIASES = {
    "ARI": "AZ",   # Arizona Diamondbacks
    "SFG": "SF",   # San Francisco Giants
    "WAS": "WSH",  # Washington Nationals
}


def canonical_team(abbr: str) -> str:
    return TEAM_ALIASES.get(abbr, abbr)


def _load(name: str, default):
    path = os.path.join(_DATA_DIR, name)
    if not os.path.exists(path):
        return default
    try:
        with open(path) as f:
            return json.load(f)
    except Exception:
        return default


def standings() -> list[dict]:
    return _load("standings.json", [])


def picks() -> list[dict]:
    return _load("picks.json", [])


def team_counts() -> dict[str, int]:
    """Returns counts keyed by *canonical* (API) team abbreviation, so the
    schedule builder can sum historic + live counts without duplication."""
    raw = _load("team_counts.json", {})
    out: dict[str, int] = {}
    for k, v in raw.items():
        canon = canonical_team(k)
        out[canon] = out.get(canon, 0) + int(v)
    return out
